# #Question 1


In [14]:
import numpy as np
array=np.arange(2,51,3)
print(array)
print(type(array))

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]
<class 'numpy.ndarray'>


# Question 2

In [33]:
import numpy as np
lst=[]
lst2=[]
for i in range(5):
    n1=int(input("Enter elements for list1: "))
    lst.append(n1)
    n2=int(input("Enter elements for list2: "))
    lst2.append(n2)
lst=np.array(lst)
lst2=np.array(lst2)
a=lst+lst2
print(a)
print(numpy.sort(a))
print(lst)
print(type(lst))
print(lst2)
print(type(lst2))

Enter elements for list1: 1
Enter elements for list2: 5
Enter elements for list1: 7
Enter elements for list2: 6
Enter elements for list1: 9
Enter elements for list2: 84
Enter elements for list1: 35
Enter elements for list2: 987
Enter elements for list1: 26
Enter elements for list2: 59
[   6   13   93 1022   85]
[   6   13   85   93 1022]
[ 1  7  9 35 26]
<class 'numpy.ndarray'>
[  5   6  84 987  59]
<class 'numpy.ndarray'>


# Question 3

In [35]:
array=np.array([[1,2,3,4],[9,8,7,6]])
print(array.ndim)
print(array.shape)
print(array)

2
(2, 4)
[[1 2 3 4]
 [9 8 7 6]]


# Question 4

In [38]:
import numpy as np
arr=np.expand_dims([1,2,3,4],axis=1)
print(arr)
print(type(arr))
print(arr.ndim)

[[1]
 [2]
 [3]
 [4]]
<class 'numpy.ndarray'>
2


## Question 5

In [25]:
import numpy
square1=numpy.array([[1,2,3],[4,5,6]])
square2=numpy.array([[66,15,4],[34,2,18]])
square1=numpy.square(square1)
square2=numpy.square(square2)
print(square1,"\n",square2)
print(type(square1))
square=numpy.vstack(square1)
squares=numpy.hstack(square1)
print(square)
print(squares)
#Similarily with square2

[[ 1  4  9]
 [16 25 36]] 
 [[4356  225   16]
 [1156    4  324]]
<class 'numpy.ndarray'>
[[ 1  4  9]
 [16 25 36]]
[ 1  4  9 16 25 36]


# Question 6

In [29]:
import numpy
import pandas
fruits=pandas.array(["apple","orange","mango","banana","kiwi","mango","orange","apple","grapes"])
print(fruits.unique())
print(fruits.value_counts())

<StringArray>
['apple', 'orange', 'mango', 'banana', 'kiwi', 'grapes']
Length: 6, dtype: string
mango     2
apple     2
orange    2
banana    1
kiwi      1
grapes    1
dtype: Int64
